### ISSUE TITLE
Incorrect Warehouses on PDF

### ISSUE THREAD

**Issue by aljawaid** [caos30/dolibarr_stocktransfers_module#2]
**Not sure how to do this but `Almacén` needs to be translated to the dolibarr warehouse location.**  The field seems incorrect.

https://github.com/caos30/dolibarr_stocktransfers_module/blob/dccf18565fe76bf8bc1a7e2138a6ead5b3b1096e/lib/views/pdf.php#L73

https://github.com/caos30/dolibarr_stocktransfers_module/blob/dccf18565fe76bf8bc1a7e2138a6ead5b3b1096e/lib/views/pdf.php#L74

![image](https://user-images.githubusercontent.com/10233708/43554820-9b7abfd4-95ee-11e8-9de2-a3d2a639999d.png)

**Comment by caos30** [comment]
Ok, check it again, please. I make some corrections. Also i improved some minor interface issues on the transfer list view. So, i upgraded the version to 1.5. 

I'm sorry by the delay of time to publish the bugfixes.

**Comment by aljawaid** [comment]
![image](https://user-images.githubusercontent.com/10233708/44617000-0554de00-a853-11e8-9bb8-99e8683bb5aa.png)

On v1.5 please see the above suggestions.

**Comment by aljawaid** [comment]
This was also tested on v7.0.3 using the module v1.5

**Comment by caos30** [comment]
It probably some of the issues you marked in your last screenshot only appears on Dolibarr 7. See my capture about the "same" PDF on Dolibarr 5:
![seleccio_380](https://user-images.githubusercontent.com/1767547/44624344-97cf9e80-a8a0-11e8-8241-47f4294a7fcf.png)
As you see, these two issues there not exist: warehouses names and company logo. 
Regarding the other "issues" i agree with you that are good suggestions. 

So i will need a little of free time to install the Dolibarr 7 to be able to work on it, bugfixes and suggestions.

**Comment by caos30** [comment]
@aljawaid i fixed all these questions and other questions regarding the PDF in the new version 1.9

In fact, i re-do the design of the PDF (i hope you find it more "cool"). And added a settings section for the module, where you can choose some of the things that you requested in this issue and others.

For example. Now is possible to choose if you wants to show "prices" of the products, for get an estimation of the transferred stock. Etc.

Anyway, i close this issue and please open a new one if you have other suggestions. Thanks man! i hope you are well!!

Sergi
